# Generated by Django 4.1.2 on 2022-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_explict',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
