# Generated by Django 4.1.2 on 2022-10-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_rename_is_explict_album_is_explicit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='is_explicit',
            new_name='is_approved_by_admin',
        ),
    ]
