# Generated by Django 4.1.2 on 2022-10-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_album_created_album_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creation_date',
        ),
    ]
