# Generated by Django 4.1.2 on 2022-10-22 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='sond.mp3', upload_to='song_audios', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='song_covers'),
        ),
    ]
