# Generated by Django 4.1.2 on 2022-10-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_song_audio_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(default='New song', max_length=200),
        ),
    ]
