# Generated by Django 4.1.2 on 2022-10-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_remove_song_name_song_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_name',
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='New Album', max_length=200),
        ),
    ]
