# Generated by Django 4.1.2 on 2022-10-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_remove_song_song_name_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
    ]
