# Generated by Django 4.1.2 on 2022-10-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_remove_song_audio_remove_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='song_covers'),
        ),
    ]
