# Generated by Django 4.1.2 on 2022-10-22 23:33

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='sond.mp3', upload_to='song_audios', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='logo.png', upload_to='song_covers'),
        ),
    ]
