# Generated by Django 4.1.2 on 2022-10-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_alter_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
